version: "3.8"

services:
  medical-agent:
    build: .
    container_name: medical-agent
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./memory:/app/memory
    command: streamlit run app.py
